@PaddleBilling.Playground.Web_HostAddress = http://localhost:5184

GET {{PaddleBilling.Playground.Web_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{PaddleBilling.Playground.Web_HostAddress}}/api/webhooks/
Accept: application/json

{
  "event_id": "evt_01hv8gq3cywt48xmwh3hqec1ty",
  "event_type": "address.created",
  "occurred_at": "2024-04-12T06:42:59.102202Z",
  "notification_id": "ntf_01hv8gq3ez64ktsbv34bpqrqfp",
  "data": {
    "id": "add_01hv8gq3318ktkfengj2r75gfx",
    "city": "New York",
    "region": "NY",
    "status": "active",
    "created_at": "2024-04-12T06:42:58.785Z",
    "first_line": "4050 Jefferson Plaza, 41st Floor",
    "updated_at": "2024-04-12T06:42:58.785Z",
    "custom_data": null,
    "customer_id": "ctm_01hv6y1jedq4p1n0yqn5ba3ky4",
    "description": "Head Office",
    "import_meta": null,
    "postal_code": "10021",
    "second_line": null,
    "country_code": "US"
  }
}