name: Pack and Publish Projects

on:
  push:
    tags:
      - 'v*'

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Create output directory
        run: mkdir -p Output

      - name: Pack and publish all eligible projects
        run: |
          projectPaths=(
            "src/PaddleBilling.Models/PaddleBilling.Models.csproj"
            "src/PaddleBilling.Http/PaddleBilling.Http.csproj"
            "src/PaddleBilling.Webhooks/PaddleBilling.Webhooks.csproj"
            "src/PaddleBilling.Utils/PaddleBilling.Utils.csproj"
            "src/PaddleBilling.Models.Json/PaddleBilling.Models.Json.csproj"
            "src/PaddleBilling.Models.Json.Aot/PaddleBilling.Models.Json.Aot.csproj"
          )
          outputBasePath="Output"

          # Loop through each project, pack, and publish
          for projectPath in "${projectPaths[@]}"; do
            projectName=$(basename $projectPath .csproj)
            outputPath="$outputBasePath/$projectName"

            echo "Packing $projectName..."
            mkdir -p "$outputPath"
            dotnet pack $projectPath --configuration Release --output "$outputPath"
            echo "Done packing $projectName!"

            # Publish to NuGet.org
            echo "Publishing $projectName..."
            for nupkg in "$outputPath"/*.nupkg; do
              if [ -f "$nupkg" ]; then
                dotnet nuget push "$nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
                echo "Published $nupkg!"
              fi
            done
          done
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
